from typing import Protocol, List
from core.types.document import Document

class IVectorStore(Protocol):
    def add_documents(self, documents: List[Document]) -> None: ...
    def query(self, query: str, top_k: int = 5) -> List[Document]: ...
    def delete(self, doc_ids: List[str]) -> None: ...
